.github/CODEOWNERS
.github/workflows/tfsec_pr_commenter.yml
README.md
main.tf
modules/internal-k8-infra/data.tf
modules/internal-k8-infra/main.tf
modules/internal-k8-infra/provider.tf
modules/internal-k8-infra/variables.tf
modules/internal-k8-infra/versions.tf
provider.tf
variables.tf
versions.tf

**Problem:**
1. No instructions were provided on authenticating to the cluster
2. We were not setting a version on the terraform provider. I set this to the max provided by spacelift. To go beyond this version we'll need to consider using the OpenTofu backend/provider.
3. We didn't have a CODEOWNERS
4. Permissions should not have been given as administrator
5. spotinst has 3 item currently being deployed. From the documentation I can find `spotinst/kubernetes-controller/ocean` seems like it was a mistake to add this
6. We had no automatic checking of terraform in the CI pipeline
**Solution:**
1. Adding all of the above items
**Testing:**
1. Will be checking the terraform plan

[IBCDPE-939] Correcting some issues

---

modules/k8s-node-autoscaler/data.tf
modules/k8s-node-autoscaler/main.tf
modules/sage-aws-eks/main.tf

https://sagebionetworks.jira.com/browse/IT-2871
Update default storage to be gp3

Update default storage to be gp3

---

common-resources/policies/main.tf
common-resources/policies/outputs.tf
common-resources/policies/warn-for-drift-reconciliation.rego
dev/spacelift/dpe-sandbox/main.tf
dev/stacks/dpe-sandbox-k8s-deployments/main.tf
dev/stacks/dpe-sandbox-k8s-deployments/provider.tf
main.tf
modules/main.tf
modules/spacelift-private-worker/README.md
modules/spacelift-private-worker/data.tf
modules/spacelift-private-worker/main.tf
modules/spacelift-private-worker/provider.tf
modules/spacelift-private-worker/variables.tf

**Problem:**
1. I wanted to take a little time and explore this enterprise feature while we had trial access. Private workers allow us to use drift detection for spacelift stacks.
**Solution:**
1. I created a terraform module for us to use that deploys private workers to a k8s cluster. I added notes in the readme about it as well so we can pick it up again in the future if we want to use this feature.
**Testing:**
1. I was able to deploy the private workers and turn on drift detection. See #dpe-topics slack channel.

[IBCDPE-935] private worker pool module

---

modules/victoria-metrics/versions.tf

**Problem:**
1. When a helm release fails during a Terraform apply the "blast radius" can be quite large and put the Terraform state into a bad state that requires quite a lot of "massaging" to get it back into a working state.
**Solution:**
1. Move the deployment model to ArgoCD which has significantly better tooling to handle deploying of kubernetes resources.
2. Terraform is responsible for deploying the initial set of applications to K8s, in addition to the resource definitions that ArgoCD uses to deploy further applications on the cluster.
3. Docs on ArgoCD: https://argo-cd.readthedocs.io/en/stable/
**Overview of deployment steps:**
1. Spacelift deploys out spacelift specific resources like the 2 stacks (Infrastructure, and k8s deployment resources)
2. The Infrastrucure stack deploys …

[IBCDPE-1034] Move deployment model to ArgoCD

---

README.md
deployments/stacks/dpe-k8s-deployments/main.tf
deployments/stacks/dpe-k8s/main.tf
main.tf
modules/main.tf
modules/sage-aws-eks/data.tf
modules/sage-aws-eks/main.tf

**Problem:**
1. As a user with a Developer level role I do not have access to the EKS cluster in any way.
**Solution:**
1. Creating an access entry for both Administrator and Developer SSO roles that have an EKS policy to access resources on the cluster
2. This gives cluster level read access: https://docs.aws.amazon.com/eks/latest/userguide/access-policies.html
**Testing:**
1. I updated my kube config and verified I could access resources from both sso roles
3. I tested that I was able to view all resources and perform port-forwarding sessions

[IBCDPE-1005] eks developer role

---

deployments/spacelift/dpe-k8s/main.tf
deployments/stacks/dpe-k8s-deployments/main.tf
deployments/stacks/dpe-k8s-deployments/variables.tf
modules/main.tf
modules/sage-aws-eks-addons/README.md
modules/sage-aws-eks-addons/main.tf
modules/sage-aws-eks-addons/variables.tf

**Problem:**
1. The automated install of AWS Guard duty added resources not managed by terraform and caused failures when tearing down the related infa.
**Solution:**
1. Implement: https://docs.aws.amazon.com/guardduty/latest/ug/managing-gdu-agent-eks-manually.html
**Testing:**
1. I tested the install of Guard Duty, and verified pods came up healthy. And we have healthy within the AWS Guard Duty console.

[IBCDPE-1007] Manual guardduty install

---

deployments/stacks/dpe-k8s-deployments/main.tf
modules/main.tf
modules/postgres-cloud-native/main.tf
modules/postgres-cloud-native/resources/kustomization.yaml
modules/postgres-cloud-native/resources/pooler.yaml

Problem:
1. Looking at database stats Apache airflow was taking all 100 connections and not giving them up:
From docs I read this is a known item and their own recommendation is to use pgbouncer as a connection pooler.
Solution:
1. The cloud native PG instance has an easy way to implement a connection pooler. Turning it on and pointing the connection secret to the connection pooler.
Testing:
1. Will deploy and test on the sandbox cluster.

[IBCDPE-1004] Create connection pooler

---

modules/apache-airflow/templates/values.yaml

**Problem:**
1. Usage of the kubernetes executor requires setting up a remote write solution to write logs to (Like S3).
2. Because of the volatile nature of running the cluster on spot instances I was seeing that components of airflow were going down because the node was taken out of the cluster.
**Solution:**
1. Fall back to celery executor.
2. Bump replicas up for core airflow components to allow scheduling, and running of tasks in high availability. The pod anti affinity should also cause the pods to be scheduled on different nodes, giving up more uptime.
**Testing:**
1. I verified this on the sandbox cluster:

[IBCDPE-1004] Move back to celery executor

---

modules/apache-airflow/README.md
modules/apache-airflow/templates/values.yaml

**Problem:**
1. `ImportError: unusual_prefix_b22621ef2028bf7db4581afeff23e3f182d62fc3_trending-projects-snapshot-dag.SnapshotMetrics was not found in allow list for deserialization imports. To allow it, add it to allowed_deserialization_classes in the configuration`
2. All of the classes that are passed around are not explicitly allowed, running into this error.
**Solution:**
1. Adding an environment variable that is supposed to allow this to allow anything so we don't need to go in and re-deploy airflow.
**Testing:**
1. Verified after deploying changes that the content is making it through by testing this dag: https://github.com/Sage-Bionetworks-Workflows/orca-recipes/blob/test-deserialization/dags/testing-deserialization.py

[IBCDPE-1004] Set env for class deserialization

---

deployments/main.tf
modules/apache-airflow/templates/values.yaml

**Problem:**
1. EBS volumes being used for mounted storage within the EKS cluster can only be re-mounted in the same AZ that it was created in. This is a problem as Spot IO when it provisions new nodes for the clusters does not use this context to know when to provision another cluster in the appropriate AZ. This leads to pods being stuck in pending and not scheduled.
**Solution:**
1. Fall back to a single AZ for now. Later on we'll determine a more robust solution to span AZs for High availability.

[IBCDPE-1004] Pull back to single AZ

---

deployments/spacelift/dpe-k8s/main.tf

**Problem:**
1. See description on https://github.com/spacelift-io/terraform-provider-spacelift/issues/565
**Solution:**
1. Add trigger_always so that even if a value of a variable being passed along did not change, the dependent stack will still run. This is to fix some issues that @BWMac identified early on when we were incrementing a module version in both the `modules/*` directory, and updating it's usage in `deployments/stacks/*`. We previously needed to run this in 2 commits, 1st commit was to get the admin stack to run, 2nd commit was to use the new module version in the deployment.
**Testing:**
1. Adding this now and will verify the next time we have a module version update to do.

Add trigger-always on dependency reference

---

modules/apache-airflow/templates/values.yaml

**Problem:**
1. Redis goes down after around a month because the persistent volume gets deleted. My suspicion is that something is occurring with the spot instances that is causing issues.
**Solution:**
1. Move several pods to on-demand instances instead of spot instances to make sure they have sufficient up-time always, and prevent any issues with persistent volumes from detaching.
**Testing:**
1. Will be verifying in dev before applying to prod.

Moving airflow to on-demand

---

deployments/main.tf
deployments/spacelift/dpe-k8s/main.tf
deployments/spacelift/dpe-k8s/variables.tf
deployments/stacks/dpe-k8s-deployments/main.tf
deployments/stacks/dpe-k8s-deployments/variables.tf
deployments/stacks/dpe-k8s/main.tf
deployments/stacks/dpe-k8s/outputs.tf
deployments/stacks/dpe-k8s/variables.tf
modules/sage-aws-eks/main.tf
modules/sage-aws-eks/variables.tf
modules/sage-aws-vpc/main.tf
modules/sage-aws-vpc/ouputs.tf
modules/sage-aws-vpc/variables.tf

Initial comment chain on issue: https://github.com/Sage-Bionetworks-Workflows/eks-stack/pull/35#discussion_r1790712362
**Problem:**
1. Khai had some recommendations on VPC sizing for the EKS cluster
2. The EKS Best Practices Guide says:
> Kubernetes worker nodes can run in the cluster subnets, but it is not recommended. During [cluster upgrades](https://aws.github.io/aws-eks-best-practices/upgrades/#verify-available-ip-addresses) Amazon EKS provisions additional ENIs in the cluster subnets. When your cluster scales out, worker nodes and pods may consume the available IPs in the cluster subnet.
**Solution:**
1. Moving VPC subnets to `/20` subnet mask which is 4094 hosts
2. Moving the EKS control plane subnets (2 AZs) to their own subnet range
3. Moving the worker subnets (3 AZs) to their …

[IBCDPE-1097] Shrink vpc subnets and move worker nodes

---

modules/apache-airflow/templates/values.yaml

**Problem:**
1. The config value to use regex was changed in 2.8.2 of airflow: https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#allowed-deserialization-classes-regexp
**Solution:**
1. Updated to the new value
**Testing:**
1. I pushed this change out and verified it was working 🤠

[IBCDPE-1111] Point to updated config value

---

modules/signoz/main.tf
modules/signoz/templates/values.yaml

**Problem:**
1. SigNoz had a few version updates which include bug fixes/features.
**Solution:**
1. Upgrade the helm chart version
2. Port over the values file into the new values file.
**Testing:**
1. This was deployed to the dpe sandbox cluster to verify deployment
**Upgrade process:**
1. Update local helm repo `helm repo update` (See https://signoz.io/docs/install/kubernetes/others/ for setting up helm to begin with)
2. Show new latest version of `signoz/signoz` chart: `helm search repo signoz`
4. Create new `values.yaml` file that is used in the new chart version `helm show values signoz/signoz > values-new.yaml`
5. Perform a diff of the existing `values.yaml` file and the `values-new.yaml`
6. Port over any configuration that is needed, and adjust anything that is new
7. Commit/deploy …

Upgrade helmchart for signoz

---

deployments/main.tf
deployments/spacelift/dpe-k8s/main.tf
deployments/spacelift/dpe-k8s/variables.tf
deployments/stacks/dpe-auth0/main.tf
deployments/stacks/dpe-auth0/variables.tf
deployments/stacks/dpe-k8s-deployments/main.tf
deployments/stacks/dpe-k8s-deployments/variables.tf
modules/envoy-gateway/main.tf
modules/envoy-gateway/templates/values.yaml
modules/signoz/main.tf
modules/signoz/resources-otel-ingress/security-policy.yaml
modules/signoz/variables.tf

**Problem:**
1. Prior to envoy gateway 1.2.x the only way to perform any sort of claim/scope based authorization was to deploy out a opa/rego server (Or other mechanism) and perform that authorization externally. They introduced (last week) the ability to defined authorization checks in the SecurityPolicy objects.
**Solution:**
1. Using a `write:telemetry` scope on the JWT claim to add an extra level of authorization checks.
2. Set the audience back to a more generic level of the entire cluster, instead of specific to telemetry.
**Testing:**
1. I tested this on our sandbox k8s cluster. I verified that without the required scopes you get an error, and with the scopes the request is accepted as expected.
When you get an error it gets rejected with an HTTP 403: …

[IBCDPE-1095] Use scope based authorization on telemetry upload route

---

deployments/main.tf

**Problem:**
1. We did not have a staging cluster set up
2. Changes for SigNoz need to be migrated to prod
**Solution:**
1. Setting up values for staging and prod to be deployed out to the prod DPE account
**Testing:**
1. Brad and I have completed a slew of testing on the dev/sandbox K8s cluster

[SCHEMATIC-139] Deploy prod and staging EKS clusters

---

modules/envoy-gateway/resources/envoy-proxy.yaml
modules/envoy-gateway/resources/traffic-policy.yaml
modules/signoz/main.tf
modules/signoz/resources-otel-ingress/http-route.yaml
modules/signoz/resources-otel-ingress/reference-grant-signoz.yaml
modules/signoz/resources-otel-ingress/security-policy.yaml

https://sagebionetworks.jira.com/browse/SCHEMATIC-215
**Problem:**
1. SigNoz (Non-Enterprise) uses their own login mechanism that doesn't support SSO/SAML; We are reluctant to add JumpCloud SSO in-front of SigNoz as it will then require a 2-step login.
2. The Sage VPN is a viable option that requires users to be on the Sage VPN. As such we need to create a route to access the UI and restrict it to the public IP address.
**Solution:**
1. Creating a route in the Envoy Gateway to access the SigNoz UI.
2. Enable proxy protocol on the AWS load balancer to support forwarding the real client IP address via the `X-Forwarded-For` header.
3. Use an `authorization` SecurityPolicy to restrict access to the SigNoz HTTP route
**Testing:**
- I verified that the URL is accessible via the `dev` url:

[SCHEMATIC-215] Enable ingress for SigNoz UI

---

deployments/stacks/dpe-k8s-deployments/main.tf
modules/trivy-operator/main.tf
modules/trivy-operator/templates/values-trivy-operator.yaml

Problem:
1. https://github.com/aquasecurity/trivy-operator/issues/2251 describes the given issue for the current version of the trivy operator. It is not fully-compatible with the 1.31 upgrade of AWS EKS.
Solution:
1. Upgrade to the latest trivy operator helm chart of 0.26.1
Testing:
I verified that resources that were not showing before (Software bill of materials, and vulnerability reports) are correctly generating:

[DPE-1248] Upgrade trivy operator for AWS EKS 1.31 upgrade

---

deployments/stacks/dpe-k8s/main.tf
modules/s3-bucket/main.tf
modules/s3-bucket/variables.tf

- A public S3 bucket is needed in the DPE account in order to handle the creation and access of croissant files created from Synapse Datasets. This [design doc describes](https://sagebionetworks.jira.com/wiki/spaces/DPE/pages/4006379521/DPE-1234+Automate+Synapse+Dataset+to+Croissant+JSON-LD+Files) the overall process for getting this data out of Snowflake and into these croissant files.
- Updating the s3 bucket module to support creating the bucket with public availability
- Add the creation of an S3 bucket to the DPE Prod stack so it will be created in the `org-sagebase-dpe-prod` AWS account
- I was able to verify in the DPE test AWS account that I could create an S3 bucket without public access, then after flipping the boolean, observe that the bucket could be listed by the public, and …

[DPE-1234] Create S3 croissant bucket in DPE aws account

---

modules/apache-airflow/templates/values.yaml

- The current version of apache airflow 2.9.3 is out of date and is running into some crashing issues in production.
- Update the deployment images and values for apache airflow to follow the latest available at https://github.com/apache/airflow/blob/main/chart/values.yaml
- Remove invalid configuration that cannot be applied in the values.yaml file since apache has not released a new helm chart version, however, the updated values.yaml file is sufficient for updating the deployed containers.
- I deployed this branch to the `dpe-k8-sandbox` cluster and verified that 1) The instances could start up as expected from nothing deployed to the cluster, and 2) I could run a DAG within the apache airflow UI.

[DPE-1276] Update airflow values.yaml to use a new airflow version

---

deployments/stacks/dpe-k8s/main.tf
modules/s3-bucket/main.tf
modules/s3-bucket/variables.tf

- CORS needs to be enabled on the S3 bucket in order to be surfaced in any portal as detailed in this message: https://sagebionetworks.jira.com/browse/PORTALS-3539?focusedCommentId=245688
- Creating a resource defined in this document: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_cors_configuration to support creating CORS rules for the bucket
- Setting the Croissant S3 bucket to use CORS
- Will be reviewing the terraform plan and apply

[PORTALS-3539] Support enabling cors for S3 bucket

---

modules/apache-airflow/templates/values.yaml

I'm seeing issues with lack of response either from the webserver or the scheduler for the Airflow namespace when trying to unpause and monitor Airflow DAGs:
When unpausing a DAG, it gets hung up and the connection to the port closes. Sometimes ending up in a perpetual restart loop:
Attempt to improve the responsiveness by:

[DPE-1266] Improve responsiveness of webserver pod

---

deployments/stacks/dpe-k8s/main.tf
deployments/stacks/dpe-k8s/outputs.tf
modules/aws-api-gateway/README.md
modules/aws-api-gateway/main.tf
modules/aws-api-gateway/outputs.tf
modules/aws-api-gateway/variables.tf
modules/aws-api-gateway/versions.tf
modules/aws-sqs/README.md
modules/aws-sqs/main.tf
modules/aws-sqs/outputs.tf
modules/aws-sqs/variables.tf
modules/aws-sqs/versions.tf

We do not currently have reusable IaC components to spin up SQS queues.
Implemented Terraform modules to create an AWS API Gateway and SQS queues that integrate with a specified API Gateway. With both of these components, we can send requests to the API Gateway and route them to appropriate SQS queues which can then be polled by downstream processes. This implementation allows us to have multiple SQS queues per API Gateway by simply assigning one route to each queue. This is just one way we could take a polling approach to receive messages generated by Synapse Webhooks. Another way we might want to look into is a push-based approach with SNS topics that downstream resources subscribe to. 
For the purposes of SYNPY-1587, I created an [Airflow …

[SYNPY-1587] Adds AWS API Gateway & SQS modules

---

modules/postgres-cloud-native/templates/cluster-values.yaml

- The Postgres DB ran out of storage
- Increase to 30Gi
- Will be testing out the deployment

Increase storage size from 8Gi to 30Gi in cluster configuration

---

modules/sage-aws-eks/variables.tf

The current K8s cluster is reaching the end of life by October this year. See documentation [here](https://kubernetes.io/releases/#release-v1-31). 
Update to use K8s version 1.32 for now and 1.33 in the end [here](https://kubernetes.io/releases/#release-v1-33)

[feat]: upgrade K8s cluster to 1.32

---

deployments/stacks/dpe-k8s-deployments/main.tf
modules/sage-aws-k8s-node-autoscaler/main.tf
modules/sage-aws-k8s-node-autoscaler/versions.tf

- 1.33 broke the Spotinst terraform module as the filter used is no longer valid for AWS published images
- Use the commit hash provided by support
- Update source and point the stack to use the local version instead of one from the private module registery

[DPE-1423] Swap ocean-aws-k8s module to support provided commit
